version = 1
SPDX-PackageName = "gdscheck"
SPDX-PackageDownloadLocation = "https://github.com/aesc-silicon/gdscheck"

[[annotations]]
path = ".github/CODEOWNERS"
SPDX-FileCopyrightText = "2026 aesc silicon"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "tests/data/*/*gds.gz"
SPDX-FileCopyrightText = "2026 aesc silicon"
SPDX-License-Identifier = "AGPL-3.0-or-later"


[[annotations]]
path = "tests/data/*/*/*gds.gz"
SPDX-FileCopyrightText = "2026 aesc silicon"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "tests/data/*/*/*/*gds.gz"
SPDX-FileCopyrightText = "2026 aesc silicon"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "Cargo.lock"
SPDX-FileCopyrightText = "2026 aesc silicon"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "docs/**"
SPDX-FileCopyrightText = "2026 aesc silicon"
SPDX-License-Identifier = "AGPL-3.0-or-later"
