// SPDX-FileCopyrightText: 2026 aesc silicon
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//! GF180MCU variant D, against the test cases the PDK ships for its own DRC deck
//! (`libs.tech/klayout/tech/drc/testing/unit/`), vendored under
//! `tests/data/gf180mcuD/static/`.
//!
//! These differ in kind from the IHP fixtures next door. Those are generated one rule at
//! a time, so a case names the handful of violations it should produce and an exact list
//! is readable. A foundry case is one dense layout exercising a whole deck at once and
//! yields hundreds of markers, so the assertion here is the **per-rule count**: which
//! rules fire, and how often.
//!
//! What that does and does not buy:
//!
//! * It pins current behaviour. Any change in a rule, a derived layer or the geometry
//!   engine that moves a count shows up here, on real foundry geometry rather than on a
//!   pattern written to match our own implementation.
//! * It is **not** a correctness proof. The numbers are what gdscheck produces today,
//!   not what the foundry's engine produces — the two disagree on markers-per-violation
//!   by construction (an edge-pair spanning a gap versus one edge per violating pair),
//!   so they were never going to match. Where a port stands against the reference
//!   `.lyrdb` is recorded in the deck file itself and re-checked with
//!   `tools/compare-lyrdb.py`; that is the correctness question, and this is the
//!   regression gate.
//!
//! A count changing is therefore a prompt to look, not a failure on its own: confirm the
//! new number against the reference, then update it here.
//!
//! The `nplus` and `pplus` fixtures are the only two vendored here that are not
//! byte-identical to upstream: each carried four TEXT elements with a zero-length
//! STRING (an empty label), which panics gds21's `read_str` — it indexes
//! `data[len - 1]` without guarding `len == 0`. The four elements were removed, since
//! an empty label carries no DRC information. The reader bug is still a bug: a real
//! design with an empty text label would crash the same way.
//!
//! One deck is validated the other way round. The PDK ships no test case for metal
//! slotting, so `tools/gen-mslot-pattern.py` writes one: nine Metal1 plates, each
//! isolating a single MSLOT1 rule, with the expected result one violation per rule and
//! nothing else. That is a stronger assertion than a count table — it says which plate
//! each rule found — but it only covers the geometry we thought to draw, so it is a
//! complement to a foundry case rather than a substitute.
//!
//! Two decks are checked the other way round entirely. `offgrid` and `acute` run against
//! patterns generated by `gen/gf180mcuD/`, each rule getting a good pattern that must
//! produce nothing and a bad one that must produce exactly what it was drawn to contain.
//! That is the direction this file should keep moving in: a per-rule count against a
//! foundry case says "about as many markers as they found", and a rule that over-reports
//! can hide inside that noise, whereas a pattern of our own makes the clean case a hard
//! zero.
//!
//! Only decks that have actually been ported appear below. The remaining fixtures are
//! vendored and waiting — adding a case for a deck that is still `rules: []` would
//! assert "no violations" and read as coverage while proving nothing.

use gdscheck::run_drc;
use rstest::rstest;

const PDK: &str = "gf180mcuD";
const DATA: &str = "tests/data/gf180mcuD/static";
const GENERATED: &str = "tests/data/gf180mcuD/generated";

/// Violation count per rule id, sorted by id, for a fixture under `static/`.
fn counts(deck: &str, gds: &str, topcell: &str) -> Vec<(String, usize)> {
    counts_at(deck, &format!("{DATA}/{gds}"), topcell)
}

/// The same, for a fixture anywhere.
fn counts_at(deck: &str, path: &str, topcell: &str) -> Vec<(String, usize)> {
    let violations = run_drc(path, PDK, &[deck], None, topcell, true).expect("DRC run failed");
    let mut by_rule: std::collections::BTreeMap<String, usize> = Default::default();
    for v in violations {
        *by_rule.entry(v.rule_id).or_default() += 1;
    }
    by_rule.into_iter().collect()
}

fn assert_counts(deck: &str, gds: &str, topcell: &str, expected: &[(&str, usize)]) {
    let want: Vec<(String, usize)> = expected
        .iter()
        .map(|(r, n)| ((*r).to_string(), *n))
        .collect();
    assert_eq!(counts(deck, gds, topcell), want);
}

// --- N-well ---
//
// Every rule in the deck fires on this case, which is the first thing worth knowing: a
// rule that silently matches nothing is the failure mode a skeleton invites.

#[rstest]
#[case::nwell(
    "nwell",
    "nwell.gds.gz",
    "7_4_NWELL",
    &[
        ("NW.1a_LV", 79),
        ("NW.1a_MV", 122),
        ("NW.1b_LV", 2),
        ("NW.1b_MV", 4),
        ("NW.2a_LV", 4),
        ("NW.2a_MV", 10),
        ("NW.2b_LV", 13),
        ("NW.2b_MV", 24),
        ("NW.3", 13),
        ("NW.4", 15),
        ("NW.5_LV", 4),
        ("NW.5_MV", 6),
        ("NW.6", 13),
    ]
)]
#[case::comp(
    "comp",
    "comp.gds.gz",
    "7_5_DF",
    &[
        ("DF.10", 2),
        ("DF.12", 74),
        ("DF.13_LV", 45),
        ("DF.13_MV", 45),
        ("DF.14_LV", 43),
        ("DF.14_MV", 44),
        ("DF.16_LV", 4),
        ("DF.16_MV", 4),
        ("DF.17_LV", 4),
        ("DF.17_MV", 4),
        ("DF.18", 4),
        ("DF.19_LV", 3),
        ("DF.19_MV", 3),
        ("DF.1a_LV", 97),
        ("DF.1a_MV", 167),
        ("DF.1c", 9),
        ("DF.2a_LV", 4),
        ("DF.2a_MV", 4),
        ("DF.2b", 2),
        ("DF.3a_LV", 23),
        ("DF.3a_MV", 23),
        ("DF.3b", 16),
        ("DF.3c_LV", 5),
        ("DF.4a_LV", 8),
        ("DF.4a_MV", 4),
        ("DF.4b_LV", 6),
        ("DF.4b_MV", 6),
        ("DF.4c_LV", 8),
        ("DF.4c_MV", 6),
        ("DF.4d_LV", 6),
        ("DF.4d_MV", 6),
        ("DF.4e_LV", 6),
        ("DF.4e_MV", 6),
        ("DF.5_LV", 6),
        ("DF.5_MV", 6),
        ("DF.6_LV", 3),
        ("DF.6_MV", 3),
        ("DF.7_LV", 4),
        ("DF.7_MV", 4),
        ("DF.8_LV", 6),
        ("DF.8_MV", 6),
        ("DF.9", 215),
    ]
)]
#[case::dnwell(
    "dnwell", "dnwell.gds.gz", "7_2_DNWELL",
    &[("DN.1", 462), ("DN.2a", 9), ("DN.2b", 33), ("DN.3", 118)]
)]
#[case::mcell(
    "mcell", "mcell.gds.gz", "7_17_Mcell",
    &[("MC.1", 35), ("MC.2", 21), ("MC.3", 13), ("MC.4", 6)]
)]
#[case::drc_bjt(
    "drc_bjt", "drc_bjt.gds.gz", "DRC_BJT",
    &[("BJT.1", 1), ("BJT.2", 2), ("BJT.3", 3)]
)]
#[case::lvs_bjt("lvs_bjt", "lvs_bjt.gds.gz", "LVS_BJT", &[("LVS_BJT.1", 2)])]
#[case::dummy_exclude(
    "dummy_exclude", "dummy_exclude.gds.gz", "10_8_DE",
    &[("DE.2", 3), ("DE.3", 1), ("DE.4", 2)]
)]
#[case::dualgate(
    "dualgate", "dualgate.gds.gz", "7_6_Dualgate",
    &[
        ("DV.1", 3), ("DV.2", 3), ("DV.3", 1), ("DV.5", 14),
        ("DV.6", 3), ("DV.7", 1), ("DV.8", 3), ("DV.9", 1),
    ]
)]
// The metal deck carries one rule set per level, and each fixture exercises one level,
// so only the M1.* rules fire here. That is why metal is absent from
// `every_rule_in_the_deck_fires` below - the other levels are silent by design.
#[case::metal1(
    "metal", "metal1.gds.gz", "metal1",
    &[("M1.1", 335), ("M1.2a", 14), ("M1.3", 85)]
)]
#[case::nat(
    "nat", "nat.gds.gz", "10_5_NAT",
    &[
        ("NAT.1", 2), ("NAT.10", 1), ("NAT.11", 1), ("NAT.12", 2),
        ("NAT.2", 4), ("NAT.3", 3), ("NAT.4", 36), ("NAT.5", 8),
        ("NAT.7", 2), ("NAT.8", 5),
    ]
)]
#[case::metaltop(
    "metaltop", "metaltop.gds.gz", "metaltop",
    &[("MT.1", 387), ("MT.2a", 14), ("MT.4", 85)]
)]
#[case::lvpwell(
    "lvpwell", "lvpwell.gds.gz", "7_3_LVPWELL",
    &[
        ("LPW.11", 13), ("LPW.12", 8), ("LPW.1_LV", 9), ("LPW.1_MV", 18),
        ("LPW.2a_LV", 10), ("LPW.2a_MV", 20), ("LPW.2b_LV", 5), ("LPW.2b_MV", 10),
        ("LPW.3", 49), ("LPW.5", 4),
    ]
)]
#[case::esd(
    "esd", "esd.gds.gz", "7_11_ESD",
    &[
        ("ESD.1", 2), ("ESD.10", 2), ("ESD.2", 2), ("ESD.3a", 1), ("ESD.3b", 7),
        ("ESD.5a", 2), ("ESD.5b", 2), ("ESD.7", 7), ("ESD.8", 3), ("ESD.9", 1),
        ("ESD.pl", 2),
    ]
)]
#[case::contact(
    "contact", "contact.gds.gz", "7_12_CO_Rev13_1P6M_11kA_MIMA_Gold_Bump",
    &[
        ("CO.1", 104), ("CO.10", 2), ("CO.11", 145), ("CO.2a", 8), ("CO.3", 7),
        ("CO.4", 5), ("CO.5a", 2), ("CO.5b", 4), ("CO.6", 98), ("CO.7", 2), ("CO.8", 2),
    ]
)]
#[case::sram_3p3(
    "sram_3p3", "sram_3p3.gds.gz", "sram_3p3",
    &[
        ("S.CO.3_LV", 3), ("S.CO.4_LV", 3), ("S.DF.16_LV", 4),
        ("S.DF.4c_LV", 3), ("S.M1.1_LV", 31),
    ]
)]
// Like metal, the via deck carries one rule set per level and each fixture exercises
// one, so only the V1.* rules fire here.
#[case::via1(
    "via", "via1.gds.gz", "7_14_VIA",
    &[("V1.1", 4), ("V1.2a", 2), ("V1.3a", 3), ("V1.4a", 6)]
)]
#[case::poly2(
    "poly2", "poly2.gds.gz", "7_7_Poly2",
    &[
        ("PL.11", 6), ("PL.12", 5), ("PL.1_LV", 21), ("PL.1_MV", 21),
        ("PL.1a_LV", 9), ("PL.1a_MV", 9), ("PL.2_LV", 90), ("PL.2_MV", 382),
        ("PL.3a", 42), ("PL.4_LV", 4), ("PL.4_MV", 4), ("PL.5a_LV", 4),
        ("PL.5a_MV", 4), ("PL.5b_LV", 4), ("PL.5b_MV", 4), ("PL.6", 720), ("PL.7_LV", 10),
        ("PL.7_MV", 10), ("PL.9", 11),
    ]
)]
#[case::sab(
    "sab", "sab.gds.gz", "7_10_SB",
    &[
        ("SB.1", 15), ("SB.10", 47), ("SB.13", 132), ("SB.15a", 9), ("SB.15b", 5),
        ("SB.16", 6), ("SB.2", 6), ("SB.3", 7), ("SB.4", 5), ("SB.5a", 7),
        ("SB.5b", 5), ("SB.6", 14), ("SB.7", 16), ("SB.8", 3), ("SB.9", 28),
    ]
)]
#[case::nplus(
    "nplus", "nplus.gds.gz", "7_10_Nplus",
    &[
        ("NP.1", 392), ("NP.10", 3), ("NP.2", 83), ("NP.3a", 9), ("NP.3bi", 10),
        ("NP.3bii", 4), ("NP.3ci", 17), ("NP.3cii", 2), ("NP.3d", 2), ("NP.3e", 2),
        ("NP.5a", 6), ("NP.6", 72), ("NP.7", 4), ("NP.8a", 121), ("NP.8b", 2),
        ("NP.9", 3),
    ]
)]
#[case::pplus(
    "pplus", "pplus.gds.gz", "7_11_Pplus",
    &[
        ("PP.1", 392), ("PP.10", 3), ("PP.2", 83), ("PP.3a", 21), ("PP.3bi", 2),
        ("PP.3bii", 13), ("PP.3ci", 4), ("PP.3cii", 10), ("PP.3d", 2), ("PP.3e", 2),
        ("PP.5a", 6), ("PP.6", 72), ("PP.7", 4), ("PP.8a", 121), ("PP.8b", 2),
        ("PP.9", 3),
    ]
)]
#[case::ldnmos(
    "ldnmos", "ldnmos.gds.gz", "10_12_1_MDN",
    &[
        ("MDN.1", 40), ("MDN.10a", 64), ("MDN.10ei", 3), ("MDN.10eii", 2),
        ("MDN.13a", 8), ("MDN.14", 29), ("MDN.15a", 44), ("MDN.15b", 2),
        ("MDN.17", 74), ("MDN.2a", 15), ("MDN.2b", 27), ("MDN.3a", 9),
        ("MDN.5ai", 31), ("MDN.5aii", 4), ("MDN.5b", 8), ("MDN.6", 14),
        ("MDN.6a", 6), ("MDN.7a", 274), ("MDN.8a", 7), ("MDN.8b", 13), ("MDN.9", 6),
    ]
)]
#[case::ldpmos(
    "ldpmos", "ldpmos.gds.gz", "10_12_2_MDP",
    &[
        ("MDP.1", 12), ("MDP.10a", 7), ("MDP.10b", 4), ("MDP.12", 3), ("MDP.13a", 1),
        ("MDP.15", 1), ("MDP.16a", 2), ("MDP.16b", 2), ("MDP.17c", 1), ("MDP.3ai", 91),
        ("MDP.3aii", 8), ("MDP.3b", 4), ("MDP.4a", 8), ("MDP.5", 8), ("MDP.5a", 5),
        ("MDP.6", 3), ("MDP.6a", 21), ("MDP.7", 1), ("MDP.8", 1), ("MDP.9a", 38),
        ("MDP.9ei", 6), ("MDP.9eii", 4),
    ]
)]
#[case::lres(
    "lres", "lres.gds.gz", "10_2_LRES",
    &[
        ("LRES.1", 26), ("LRES.2", 6), ("LRES.3", 8), ("LRES.4", 6), ("LRES.5", 7),
        ("LRES.6", 39), ("LRES.7", 7),
    ]
)]
#[case::pres(
    "pres", "pres.gds.gz", "10_1_PRES",
    &[
        ("PRES.1", 26), ("PRES.2", 5), ("PRES.3", 8), ("PRES.4", 5), ("PRES.5", 7),
        ("PRES.6", 39), ("PRES.7", 7),
    ]
)]
#[case::hres(
    "hres", "hres.gds.gz", "10_3_HRES",
    &[
        ("HRES.1", 5), ("HRES.2", 59), ("HRES.3", 6), ("HRES.4", 23), ("HRES.5", 5),
        ("HRES.6", 5), ("HRES.7", 22), ("HRES.8", 27), ("HRES.9", 5),
    ]
)]
#[case::otp_mk(
    "otp_mk", "otp_mk.gds.gz", "10_10_OTP",
    &[
        ("O.CO.7", 2), ("O.DF.3a", 9), ("O.DF.6", 16), ("O.DF.9", 4), ("O.PL.3a", 10),
        ("O.PL.4", 9), ("O.SB.13_LV", 53), ("O.SB.13_MV", 1), ("O.SB.2", 5),
        ("O.SB.3", 4), ("O.SB.5b_LV", 4), ("O.SB.9", 1),
    ]
)]
#[case::ymtp_mk(
    "ymtp_mk", "ymtp_mk.gds.gz", "10_13_YMTP",
    &[
        ("Y.DF.16_LV", 4), ("Y.DF.16_MV", 4), ("Y.DF.6_MV", 14), ("Y.NW.2b_LV", 13),
        ("Y.NW.2b_MV", 26), ("Y.PL.1_LV", 99), ("Y.PL.1_MV", 119), ("Y.PL.2_LV", 68),
        ("Y.PL.2_MV", 164), ("Y.PL.4_MV", 6), ("Y.PL.5a_LV", 8), ("Y.PL.5a_MV", 4),
        ("Y.PL.5b_LV", 8), ("Y.PL.5b_MV", 4),
    ]
)]
#[case::sram_5p0(
    "sram_5p0", "sram_5p0.gds.gz", "sram_5p0",
    &[
        ("S.CO.4_MV", 3), ("S.DF.16_MV", 4), ("S.DF.4c_MV", 3), ("S.DF.6_MV", 13),
        ("S.DF.7_MV", 4), ("S.DF.8_MV", 3), ("S.PL.5a_MV", 4),
    ]
)]
#[case::efuse(
    "efuse", "efuse.gds.gz", "10_11_EFUSE",
    &[
        ("EF.01", 38), ("EF.04b", 75), ("EF.04c", 23), ("EF.04d", 16), ("EF.05", 38),
        ("EF.10", 38), ("EF.11", 5), ("EF.12", 19), ("EF.13", 4), ("EF.14", 6),
        ("EF.15", 12), ("EF.17", 6), ("EF.18", 46), ("EF.19", 21), ("EF.20", 50),
    ]
)]
#[case::mim_b(
    "mim_b", "mim_b.gds.gz", "10_4_2_MIM_OptionB",
    &[
        ("MIMTM.1", 4), ("MIMTM.10", 3), ("MIMTM.2", 7), ("MIMTM.3", 61),
        ("MIMTM.4", 6), ("MIMTM.5", 6), ("MIMTM.6", 4), ("MIMTM.7", 2490),
        ("MIMTM.8a", 60), ("MIMTM.8b", 1), ("MIMTM.9", 4),
    ]
)]
#[case::antenna(
    "antenna", "antenna-1.gds.gz", "8_0_ANT",
    &[
        ("ANT.1", 1), ("ANT.16_i_ANT.10", 1), ("ANT.16_i_ANT.11", 1),
        ("ANT.16_i_ANT.12", 1), ("ANT.16_i_ANT.2", 1), ("ANT.16_i_ANT.3", 1),
        ("ANT.16_i_ANT.4", 1), ("ANT.16_i_ANT.5", 1), ("ANT.16_i_ANT.6", 4),
        ("ANT.16_i_ANT.9", 1), ("ANT.8", 1),
    ]
)]
fn static_fixture(
    #[case] deck: &str,
    #[case] gds: &str,
    #[case] topcell: &str,
    #[case] expected: &[(&str, usize)],
) {
    assert_counts(deck, gds, topcell, expected);
}

/// Every rule the deck declares must appear in the run above. A rule that resolves to an
/// empty derived layer produces no violations and no error, so without this a typo in a
/// layer name looks exactly like a clean design.
#[rstest]
#[case::nwell("nwell", "nwell.gds.gz", "7_4_NWELL")]
#[case::comp("comp", "comp.gds.gz", "7_5_DF")]
#[case::mcell("mcell", "mcell.gds.gz", "7_17_Mcell")]
#[case::drc_bjt("drc_bjt", "drc_bjt.gds.gz", "DRC_BJT")]
#[case::lvs_bjt("lvs_bjt", "lvs_bjt.gds.gz", "LVS_BJT")]
#[case::dummy_exclude("dummy_exclude", "dummy_exclude.gds.gz", "10_8_DE")]
#[case::dualgate("dualgate", "dualgate.gds.gz", "7_6_Dualgate")]
#[case::nat("nat", "nat.gds.gz", "10_5_NAT")]
#[case::metaltop("metaltop", "metaltop.gds.gz", "metaltop")]
#[case::lvpwell("lvpwell", "lvpwell.gds.gz", "7_3_LVPWELL")]
#[case::esd("esd", "esd.gds.gz", "7_11_ESD")]
#[case::contact("contact", "contact.gds.gz", "7_12_CO_Rev13_1P6M_11kA_MIMA_Gold_Bump")]
#[case::sram_3p3("sram_3p3", "sram_3p3.gds.gz", "sram_3p3")]
#[case::poly2("poly2", "poly2.gds.gz", "7_7_Poly2")]
#[case::sab("sab", "sab.gds.gz", "7_10_SB")]
#[case::nplus("nplus", "nplus.gds.gz", "7_10_Nplus")]
#[case::pplus("pplus", "pplus.gds.gz", "7_11_Pplus")]
#[case::ldnmos("ldnmos", "ldnmos.gds.gz", "10_12_1_MDN")]
#[case::ldpmos("ldpmos", "ldpmos.gds.gz", "10_12_2_MDP")]
#[case::lres("lres", "lres.gds.gz", "10_2_LRES")]
#[case::pres("pres", "pres.gds.gz", "10_1_PRES")]
#[case::hres("hres", "hres.gds.gz", "10_3_HRES")]
#[case::otp_mk("otp_mk", "otp_mk.gds.gz", "10_10_OTP")]
#[case::ymtp_mk("ymtp_mk", "ymtp_mk.gds.gz", "10_13_YMTP")]
#[case::sram_5p0("sram_5p0", "sram_5p0.gds.gz", "sram_5p0")]
#[case::efuse("efuse", "efuse.gds.gz", "10_11_EFUSE")]
#[case::mim_b("mim_b", "mim_b.gds.gz", "10_4_2_MIM_OptionB")]
fn every_rule_in_the_deck_fires(#[case] deck: &str, #[case] gds: &str, #[case] topcell: &str) {
    let pdk = gdscheck::pdk::PdkConfig::for_process(PDK).unwrap();
    let declared: std::collections::BTreeSet<String> = pdk
        .load_deck(deck)
        .unwrap()
        .iter()
        .map(|r| r.id.clone())
        .collect();
    let fired: std::collections::BTreeSet<String> = counts(deck, gds, topcell)
        .into_iter()
        .map(|(r, _)| r)
        .collect();
    let silent: Vec<&String> = declared.difference(&fired).collect();
    assert!(
        silent.is_empty(),
        "deck '{deck}' declares rules that never fire on {gds}: {silent:?}"
    );
}

// --- Generated patterns ---
//
// The `offgrid` and `acute` decks are checked against patterns we draw ourselves rather
// than against a foundry case, and each rule gets two: a **good** one that must produce
// nothing and a **bad** one that must produce exactly the violations it was drawn to
// contain. That is a stronger statement than a count table can make. A foundry case only
// ever says "we found about as many markers as they did", and the two engines disagree on
// how many markers one violation is worth — so a rule that quietly over-reports can sit
// inside that noise indefinitely. Against a pattern of our own the good half is a hard
// zero, and a false positive has nowhere to hide.
//
// Sources: `gen/gf180mcuD/offgrid.rs` and `gen/gf180mcuD/acute.rs`.

/// Deck, fixture directory, and how many violations that deck's bad pattern contains.
/// Off-grid reports per vertex and the shifted edge has two; the acute pattern's triangle
/// has exactly one edge off the 45° lattice.
const GENERATED_DECKS: &[(&str, usize)] = &[("offgrid", 2), ("acute", 1)];

/// Every rule id in a deck, read from the deck itself so a rule without a fixture is a
/// failure here rather than a silent gap.
fn rule_ids(deck: &str) -> Vec<String> {
    let pdk = gdscheck::pdk::PdkConfig::for_process(PDK).expect("PDK loads");
    let rules = pdk.load_deck(deck).expect("deck loads");
    assert!(!rules.is_empty(), "deck '{deck}' is empty");
    rules.iter().map(|r| r.id.clone()).collect()
}

fn run_generated(deck: &str, id: &str, polarity: &str) -> Vec<(String, usize)> {
    counts_at(
        deck,
        &format!("{GENERATED}/{deck}/{id}.{polarity}.gds.gz"),
        "TOP",
    )
}

/// The half that matters most: legal geometry, including a 45° chamfer, produces nothing.
#[test]
fn generated_good_patterns_are_clean() {
    for (deck, _) in GENERATED_DECKS {
        for id in rule_ids(deck) {
            let got = run_generated(deck, &id, "good");
            assert!(
                got.is_empty(),
                "{deck}: {id} fired on its good pattern: {got:?}"
            );
        }
    }
}

/// And the other half: a real violation is still caught, on every layer the deck covers.
#[test]
fn generated_bad_patterns_fire() {
    for (deck, expected) in GENERATED_DECKS {
        for id in rule_ids(deck) {
            let got = run_generated(deck, &id, "bad");
            assert_eq!(
                got,
                vec![(id.clone(), *expected)],
                "{deck}: {id} should fire {expected} time(s) on its bad pattern"
            );
        }
    }
}

// --- Metal slotting ---
//
// The one deck here with no foundry test case behind it; see the generator's docstring
// for what each plate is meant to trip. Each of the nine rules fires exactly once, and
// plate B - the one with a legal slot - is silent, which is what says the slot actually
// broke the 30 um opening rather than the rule being unreachable.

#[test]
fn mslot_pattern_trips_each_metal1_rule_exactly_once() {
    let got = counts_at(
        "mslot",
        &format!("{GENERATED}/mslot.gds.gz"),
        "MSLOT_PATTERN",
    );
    let want: Vec<(String, usize)> = [
        "MSLOT1.0", "MSLOT1.1", "MSLOT1.2", "MSLOT1.3", "MSLOT1.4", "MSLOT1.5", "MSLOT1.7",
        "MSLOT1.8", "MSLOT1.9",
    ]
    .iter()
    .map(|r| ((*r).to_string(), 1))
    .collect();
    assert_eq!(got, want);
}

// --- YMTP marker, generated ---
//
// Twelve cases covering all fourteen rule ids (Y.PL.5a and Y.PL.5b are the same
// measurement upstream, so one pattern exercises both). Each is drawn inside a YMTP
// marker, with Dualgate over it where the rule is the 5 V flavour, since that is what
// makes a marker MV rather than LV.

/// Case name, and what its bad half must produce. `None` would mark a case whose
/// violation this engine does not find; there are none at present.
type YmtpCase = (&'static str, Option<&'static [(&'static str, usize)]>);

const YMTP_CASES: &[YmtpCase] = &[
    ("Y.NW.2b_LV", Some(&[("Y.NW.2b_LV", 1)])),
    ("Y.NW.2b_MV", Some(&[("Y.NW.2b_MV", 1)])),
    ("Y.DF.16_LV", Some(&[("Y.DF.16_LV", 1)])),
    ("Y.DF.16_MV", Some(&[("Y.DF.16_MV", 1)])),
    ("Y.PL.1_LV", Some(&[("Y.PL.1_LV", 2)])),
    ("Y.PL.1_MV", Some(&[("Y.PL.1_MV", 1)])),
    ("Y.PL.2_LV", Some(&[("Y.PL.2_LV", 2)])),
    ("Y.PL.2_MV", Some(&[("Y.PL.2_MV", 2)])),
    ("Y.PL.5_LV", Some(&[("Y.PL.5a_LV", 1), ("Y.PL.5b_LV", 1)])),
    ("Y.PL.5_MV", Some(&[("Y.PL.5a_MV", 1), ("Y.PL.5b_MV", 1)])),
    // A gate poly crossing its COMP, measured at right angles to the crossing: the
    // source/drain overhang for Y.DF.6_MV, the poly end cap for Y.PL.4_MV. These two were
    // the fixtures that found `polys_interact`'s missing edge-crossing test.
    ("Y.DF.6_MV", Some(&[("Y.DF.6_MV", 1)])),
    ("Y.PL.4_MV", Some(&[("Y.PL.4_MV", 1)])),
];

#[test]
fn ymtp_good_patterns_are_clean() {
    for (name, _) in YMTP_CASES {
        let got = counts_at(
            "ymtp_mk",
            &format!("{GENERATED}/ymtp_mk/{name}.good.gds.gz"),
            "TOP",
        );
        assert!(got.is_empty(), "{name} fired on its good pattern: {got:?}");
    }
}

#[test]
fn ymtp_bad_patterns_fire() {
    for (name, expected) in YMTP_CASES {
        let got = counts_at(
            "ymtp_mk",
            &format!("{GENERATED}/ymtp_mk/{name}.bad.gds.gz"),
            "TOP",
        );
        match expected {
            Some(want) => {
                let want: Vec<(String, usize)> =
                    want.iter().map(|(r, n)| ((*r).to_string(), *n)).collect();
                assert_eq!(got, want, "{name} bad pattern");
            }
            None => assert!(
                got.is_empty(),
                "{name} now fires ({got:?}) — the gap this case recorded appears to be \
                 fixed, so give it its real expectation"
            ),
        }
    }
}

// --- Gate poly, generated ---

/// `PL.6` is the `no_corner` rule: poly may not turn a right angle over active area.
///
/// The good pattern says that from three sides at once — a right-angle bend clear of any
/// COMP, a 45° turn on COMP, and a right-angle bend on COMP but inside a YMTP marker,
/// which the rule exempts. A check that had collapsed to "any bend", or to "any bend on
/// COMP", fails here rather than passing.
#[test]
fn pl6_corner_patterns() {
    let good = counts_at(
        "poly2",
        &format!("{GENERATED}/poly2/PL.6.good.gds.gz"),
        "TOP",
    );
    assert!(good.is_empty(), "PL.6 fired on its good pattern: {good:?}");

    let bad = counts_at(
        "poly2",
        &format!("{GENERATED}/poly2/PL.6.bad.gds.gz"),
        "TOP",
    );
    assert_eq!(
        bad,
        vec![("PL.6".to_string(), 2)],
        "the L's two elbow corners are inside the COMP; its other four are not"
    );
}
