// SPDX-FileCopyrightText: 2026 aesc silicon
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//! GF180MCU variant D, against the test cases the PDK ships for its own DRC deck
//! (`libs.tech/klayout/tech/drc/testing/unit/`), vendored under
//! `tests/data/gf180mcuD/static/`.
//!
//! These differ in kind from the IHP fixtures next door. Those are generated one rule at
//! a time, so a case names the handful of violations it should produce and an exact list
//! is readable. A foundry case is one dense layout exercising a whole deck at once and
//! yields hundreds of markers, so the assertion here is the **per-rule count**: which
//! rules fire, and how often.
//!
//! What that does and does not buy:
//!
//! * It pins current behaviour. Any change in a rule, a derived layer or the geometry
//!   engine that moves a count shows up here, on real foundry geometry rather than on a
//!   pattern written to match our own implementation.
//! * It is **not** a correctness proof. The numbers are what gdscheck produces today,
//!   not what the foundry's engine produces — the two disagree on markers-per-violation
//!   by construction (an edge-pair spanning a gap versus one edge per violating pair),
//!   so they were never going to match. Where a port stands against the reference
//!   `.lyrdb` is recorded in the deck file itself and re-checked with
//!   `tools/compare-lyrdb.py`; that is the correctness question, and this is the
//!   regression gate.
//!
//! A count changing is therefore a prompt to look, not a failure on its own: confirm the
//! new number against the reference, then update it here.
//!
//! The `nplus` and `pplus` fixtures are the only two vendored here that are not
//! byte-identical to upstream: each carried four TEXT elements with a zero-length
//! STRING (an empty label), which panics gds21's `read_str` — it indexes
//! `data[len - 1]` without guarding `len == 0`. The four elements were removed, since
//! an empty label carries no DRC information. The reader bug is still a bug: a real
//! design with an empty text label would crash the same way.
//!
//! Two decks are checked the other way round entirely. `offgrid` and `acute` run against
//! patterns generated by `gen/gf180mcuD/`, each rule getting a good pattern that must
//! produce nothing and a bad one that must produce exactly what it was drawn to contain.
//! That is the direction this file should keep moving in: a per-rule count against a
//! foundry case says "about as many markers as they found", and a rule that over-reports
//! can hide inside that noise, whereas a pattern of our own makes the clean case a hard
//! zero.
//!
//! Only decks that have actually been ported appear below. The remaining fixtures are
//! vendored and waiting — adding a case for a deck that is still `rules: []` would
//! assert "no violations" and read as coverage while proving nothing.

use gdscheck::run_drc;
use rstest::rstest;

const PDK: &str = "gf180mcuD";
const DATA: &str = "tests/data/gf180mcuD/static";
const GENERATED: &str = "tests/data/gf180mcuD/generated";

/// Violation count per rule id, sorted by id, for a fixture under `static/`.
fn counts(deck: &str, gds: &str, topcell: &str) -> Vec<(String, usize)> {
    counts_at(deck, &format!("{DATA}/{gds}"), topcell)
}

/// The same, for a fixture anywhere.
fn counts_at(deck: &str, path: &str, topcell: &str) -> Vec<(String, usize)> {
    let violations = run_drc(path, PDK, &[deck], None, topcell, true).expect("DRC run failed");
    let mut by_rule: std::collections::BTreeMap<String, usize> = Default::default();
    for v in violations {
        *by_rule.entry(v.rule_id).or_default() += 1;
    }
    by_rule.into_iter().collect()
}

// --- N-well ---
//
// Every rule in the deck fires on this case, which is the first thing worth knowing: a
// rule that silently matches nothing is the failure mode a skeleton invites.

// The per-rule marker counts that used to live here are gone.  What they pinned was this
// engine's own output, false positives and all, so every improvement moved a couple of
// dozen numbers and a diff of them could not say whether the port had got better or
// worse.  Two tests replace them, each answering one of the questions those numbers
// conflated: `tests/reference_score.rs` scores each deck against the report the foundry
// ships beside its own case, as a floor on violations found and a ceiling on violations
// invented, so an improvement passes and only a regression fails; and the generated
// good/bad patterns below say whether a rule is *right*, on geometry drawn here for it.

/// A real seal ring, and the shape the generated patterns are modelled on: a band 16 µm
/// wide with a 45° chamfer across each corner, its active drawn as four corner pieces and
/// four bars, the marker one annulus over the same outline, and contacts and vias 0.7 µm
/// apart filling it.  Upstream implements no GR rule at all - `guard_ring_mk` appears in
/// KLayout's deck only as an exclusion for other sections - so there is no reference to
/// score this against and the count below is a golden, not a verdict on the design.
///
/// GR.2 is the one that fires: the prime die's metal stands 8.8 µm off the marker on every
/// level, where the table asks for ten.  Everything else the ring satisfies, two of them
/// exactly - its active is 16 µm against GR.6's minimum of 16, and its contacts and vias
/// sit at 0.7000 µm against GR.7 and GR.8's 0.7.
///
/// It is also the case that found the halo the region selectors were missing: GR.2 reads
/// `metal1_prime` and its siblings, which are selections, and a selection comes back with
/// one piece per region per tile and no halo copies; five of these walls fell in a
/// neighbouring tile's core and went unreported until the count below was 130.
#[test]
fn guard_ring_on_a_real_seal_ring() {
    assert_eq!(
        counts("guard_ring", "guardring.gds.gz", "TOP"),
        vec![("GR.2".to_string(), 145)]
    );
}

/// Every rule the deck declares must appear in the run above. A rule that resolves to an
/// empty derived layer produces no violations and no error, so without this a typo in a
/// layer name looks exactly like a clean design.
#[rstest]
#[case::nwell("nwell", "nwell.gds.gz", "7_4_NWELL")]
#[case::comp("comp", "comp.gds.gz", "7_5_DF")]
#[case::mcell("mcell", "mcell.gds.gz", "7_17_Mcell")]
#[case::drc_bjt("drc_bjt", "drc_bjt.gds.gz", "DRC_BJT")]
#[case::lvs_bjt("lvs_bjt", "lvs_bjt.gds.gz", "LVS_BJT")]
#[case::dummy_exclude("dummy_exclude", "dummy_exclude.gds.gz", "10_8_DE")]
#[case::dualgate("dualgate", "dualgate.gds.gz", "7_6_Dualgate")]
#[case::nat("nat", "nat.gds.gz", "10_5_NAT")]
#[case::metaltop("metaltop", "metaltop.gds.gz", "metaltop")]
#[case::lvpwell("lvpwell", "lvpwell.gds.gz", "7_3_LVPWELL")]
#[case::esd("esd", "esd.gds.gz", "7_11_ESD")]
#[case::contact("contact", "contact.gds.gz", "7_12_CO_Rev13_1P6M_11kA_MIMA_Gold_Bump")]
#[case::sram_3p3("sram_3p3", "sram_3p3.gds.gz", "sram_3p3")]
#[case::poly2("poly2", "poly2.gds.gz", "7_7_Poly2")]
#[case::sab("sab", "sab.gds.gz", "7_10_SB")]
#[case::nplus("nplus", "nplus.gds.gz", "7_10_Nplus")]
#[case::pplus("pplus", "pplus.gds.gz", "7_11_Pplus")]
#[case::ldnmos("ldnmos", "ldnmos.gds.gz", "10_12_1_MDN")]
#[case::ldpmos("ldpmos", "ldpmos.gds.gz", "10_12_2_MDP")]
#[case::lres("lres", "lres.gds.gz", "10_2_LRES")]
#[case::pres("pres", "pres.gds.gz", "10_1_PRES")]
#[case::hres("hres", "hres.gds.gz", "10_3_HRES")]
#[case::otp_mk("otp_mk", "otp_mk.gds.gz", "10_10_OTP")]
#[case::ymtp_mk("ymtp_mk", "ymtp_mk.gds.gz", "10_13_YMTP")]
#[case::sram_5p0("sram_5p0", "sram_5p0.gds.gz", "sram_5p0")]
#[case::efuse("efuse", "efuse.gds.gz", "10_11_EFUSE")]
#[case::mim_b("mim_b", "mim_b.gds.gz", "10_4_2_MIM_OptionB")]
fn every_rule_in_the_deck_fires(#[case] deck: &str, #[case] gds: &str, #[case] topcell: &str) {
    let pdk = gdscheck::pdk::PdkConfig::for_process(PDK).unwrap();
    let declared: std::collections::BTreeSet<String> = pdk
        .load_deck(deck)
        .unwrap()
        .iter()
        .map(|r| r.id.clone())
        .collect();
    let fired: std::collections::BTreeSet<String> = counts(deck, gds, topcell)
        .into_iter()
        .map(|(r, _)| r)
        .collect();
    let silent: Vec<&String> = declared.difference(&fired).collect();
    assert!(
        silent.is_empty(),
        "deck '{deck}' declares rules that never fire on {gds}: {silent:?}"
    );
}

// --- Generated patterns ---
//
// The `offgrid` and `acute` decks are checked against patterns we draw ourselves rather
// than against a foundry case, and each rule gets two: a **good** one that must produce
// nothing and a **bad** one that must produce exactly the violations it was drawn to
// contain. That is a stronger statement than a count table can make. A foundry case only
// ever says "we found about as many markers as they did", and the two engines disagree on
// how many markers one violation is worth — so a rule that quietly over-reports can sit
// inside that noise indefinitely. Against a pattern of our own the good half is a hard
// zero, and a false positive has nowhere to hide.
//
// Sources: `gen/gf180mcuD/offgrid.rs` and `gen/gf180mcuD/acute.rs`.

/// Deck, fixture directory, and how many violations that deck's bad pattern contains.
/// Off-grid reports per vertex and the shifted edge has two; the acute pattern's triangle
/// has exactly one edge off the 45° lattice.
const GENERATED_DECKS: &[(&str, usize)] = &[("offgrid", 2), ("acute", 1)];

/// Every rule id in a deck, read from the deck itself so a rule without a fixture is a
/// failure here rather than a silent gap.
fn rule_ids(deck: &str) -> Vec<String> {
    let pdk = gdscheck::pdk::PdkConfig::for_process(PDK).expect("PDK loads");
    let rules = pdk.load_deck(deck).expect("deck loads");
    assert!(!rules.is_empty(), "deck '{deck}' is empty");
    rules.iter().map(|r| r.id.clone()).collect()
}

fn run_generated(deck: &str, id: &str, polarity: &str) -> Vec<(String, usize)> {
    counts_at(
        deck,
        &format!("{GENERATED}/{deck}/{id}.{polarity}.gds.gz"),
        "TOP",
    )
}

/// Decks where every rule has a drawn good/bad pair, and the pair means the same thing
/// for all of them: the good half is silent, and the bad half fires that rule and only
/// that rule.
///
/// This is the contract to write new patterns against.  The older decks above predate it
/// and pin exact counts through tests of their own, which says more but has to be written
/// per deck; this one costs a generator and a line here.
const PATTERN_DECKS: &[&str] = &[
    "comp",
    "contact",
    "drc_bjt",
    "cup",
    "density",
    "dnwell",
    "dualgate",
    "dummy_comp",
    "dummy_exclude",
    "dummy_metal",
    "dummy_poly2",
    "efuse",
    "esd",
    "guard_ring",
    "hres",
    "ldnmos",
    "ldpmos",
    "lres",
    "lvs_bjt",
    "lvpwell",
    "mcell",
    "nat",
    "nplus",
    "nwell",
    "otp_mk",
    "poly2",
    "sab",
    "sram_3p3",
    "sram_5p0",
    "metal",
    "metaltop",
    "mim_b",
    "mslot",
];

#[test]
fn pattern_good_halves_are_silent() {
    for deck in PATTERN_DECKS {
        for id in dedup(rule_ids(deck)) {
            let got = run_generated(deck, &id, "good");
            assert!(
                got.is_empty(),
                "{deck}: {id} good pattern is not clean: {got:?}"
            );
        }
    }
}

#[test]
fn pattern_bad_halves_fire_their_own_rule() {
    for deck in PATTERN_DECKS {
        for id in dedup(rule_ids(deck)) {
            let got = run_generated(deck, &id, "bad");
            let fired: Vec<&String> = got.iter().map(|(r, _)| r).collect();
            assert!(
                fired.contains(&&id),
                "{deck}: {id} bad pattern did not fire it: {got:?}"
            );
            // Two deck entries with the same check on the same layers at the same value
            // are one measurement under two names - GF180 floors the top metal's density
            // as both M5.4 and MT.3 - and no pattern can separate them.  Read from the
            // deck rather than listed here, so the allowance cannot outlive its reason.
            let twins = same_measurement(deck, &id);
            let others: Vec<&&String> = fired
                .iter()
                .filter(|r| **r != &id && !twins.contains(**r))
                .filter(|r| {
                    !COINCIDENT
                        .iter()
                        .any(|&(d, of, also)| d == *deck && of == id && also == r.as_str())
                })
                .collect();
            assert!(
                others.is_empty(),
                "{deck}: {id} bad pattern also fired {others:?} - a pattern should isolate \
                 its own rule"
            );
        }
    }
}

/// Rule ids in `deck` that measure exactly what `id` measures - same check, same layers,
/// same value - and so must fire wherever it does.
/// Rules a fixture may fire besides its own, because the deck makes the two coincide and
/// no geometry can tell them apart.  Twins that are literally the same check on the same
/// layers are found from the deck by [`same_measurement`]; these are the ones only the
/// rule text explains, so each carries its reason.
const COINCIDENT: &[(&str, &str, &str)] = &[
    // Upstream writes SB.4 as `separation(contact, 0.15).or(sab.and(contact))` and SB.8
    // as `contact.and(sab)`.  A contact *on* the block is the second half of one and the
    // whole of the other, so it breaks both by construction.
    ("sab", "SB.8", "SB.4"),
    // The LDNMOS gate's width is the channel plus the drift it overlaps, and MDN.11 fixes
    // that overlap at 0.4.  So a channel under MDN.3a's 0.6 leaves a gate under MDN.10a's
    // 1.2 by arithmetic, and no geometry breaks the one without the other.
    ("ldnmos", "MDN.3a", "MDN.10a"),
    // A source shared between two fingers is what MDN.13c reports, and it is also the
    // butted-tap arrangement MDN.13d joins into its own output, so the one geometry is
    // both by construction.
    ("ldnmos", "MDN.13c", "MDN.13d"),
    // MDN.13b wants the fingers to alternate source and drain.  A finger with source on
    // both sides of it, which is what MDN.13c reports, is the arrangement that is not
    // alternating - so the one geometry answers to both.
    ("ldnmos", "MDN.13c", "MDN.13b"),
    // The P side, for the same reason.
    ("ldpmos", "MDP.13c", "MDP.13b"),
    // GR.3 wants the implant over the ring's active and GR.6 wants that active 16 µm
    // wide.  Uncovering any of it is what GR.3 forbids and what narrows what GR.6
    // measures, so no geometry breaks one alone.
    ("guard_ring", "GR.3", "GR.6"),
    // MDN.4b caps the transistor's width and MDN.13a the length of the body that carries
    // it, and on this device they are the same measurement seen from two sides: the
    // foundry's own report draws MDN.13a on a body's long walls and MDN.4b on the two
    // ends between them, the same sixteen markers under both ids.
    ("ldnmos", "MDN.4b", "MDN.13a"),
    ("ldnmos", "MDN.13a", "MDN.4b"),
    // MDN.7 forbids device material under a Dualgate outside the LDMOS marker, and every
    // layer that counts as device material there is defined against the drift.  MDN.7a's
    // second half forbids drift under a Dualgate outside the marker outright, so nothing
    // can break the first without breaking the second.
    ("ldnmos", "MDN.7", "MDN.7a"),
    // NP.3d forbids an N+ active over a P+ active and NP.3e an N+ marker over a P+
    // active.  An N+ active *is* comp under the marker, so both expand to the same
    // intersection of comp, nplus and pplus and no drawing separates them.
    ("nplus", "NP.3d", "NP.3e"),
    ("nplus", "NP.3e", "NP.3d"),
    // The eFuse deck does not bound its device's dimensions, it fixes them, and the
    // numbers are not independent: 1.84 + 1.26 + 2.43 is the 5.53 µm EF.21 asks of the
    // poly end to end, and the shoulders EF.22a and EF.22b pin are what is left when the
    // link's width is taken from each pad's.  So no drawing changes one of them alone.
    ("efuse", "EF.03", "EF.21"),
    ("efuse", "EF.07", "EF.21"),
    ("efuse", "EF.09", "EF.21"),
    ("efuse", "EF.21", "EF.03"),
    ("efuse", "EF.06", "EF.22a"),
    ("efuse", "EF.08", "EF.22b"),
    ("efuse", "EF.22a", "EF.22b"),
    ("efuse", "EF.22b", "EF.22a"),
    // The shoulders are the only pair a drawing can reach through the link's own width,
    // and EF.02 fixes that width, so narrowing a shoulder is widening the link past it.
    ("efuse", "EF.22a", "EF.02"),
    ("efuse", "EF.22b", "EF.02"),
    // A shape that is no longer a rectangle has an edge that is no longer its old length,
    // and every edge of this device is pinned by something.
    ("efuse", "EF.04b", "EF.03"),
    // And a shape that is no longer a rectangle has no one width, so EF.02 - which fixes
    // the link's - reads it as the wrong one wherever the bend put it.
    ("efuse", "EF.04b", "EF.02"),
    ("efuse", "EF.04c", "EF.06"),
    ("efuse", "EF.04c", "EF.07"),
    ("efuse", "EF.04d", "EF.08"),
    ("efuse", "EF.04d", "EF.09"),
    // A contact *on* the link is also nearer to it than the 0.155 µm EF.12 allows.
    ("efuse", "EF.15", "EF.12"),
    // Metal is in the list of things EF.18 keeps off the link as well as EF.19's.
    ("efuse", "EF.19", "EF.18"),
    // A marker that overlaps an active without covering it has, by saying so, failed to
    // enclose it by the 0.24 µm DV.6 asks.
    ("dualgate", "DV.7", "DV.6"),
];

fn same_measurement(deck: &str, id: &str) -> Vec<String> {
    let pdk = gdscheck::pdk::PdkConfig::for_process(PDK).expect("PDK loads");
    let rules = pdk.load_deck(deck).expect("deck loads");
    let key = |r: &gdscheck::pdk::RuleDefinition| {
        (
            r.check.clone(),
            r.layers.iter().map(|l| l.name.clone()).collect::<Vec<_>>(),
            r.value.to_bits(),
        )
    };
    let want: Vec<_> = rules.iter().filter(|r| r.id == id).map(key).collect();
    rules
        .iter()
        .filter(|r| r.id != id && want.contains(&key(r)))
        .map(|r| r.id.clone())
        .collect()
}

fn dedup(mut ids: Vec<String>) -> Vec<String> {
    ids.sort();
    ids.dedup(); // a rule split over a space and a notch entry shares one id
    ids
}

/// The half that matters most: legal geometry, including a 45° chamfer, produces nothing.
#[test]
fn generated_good_patterns_are_clean() {
    for (deck, _) in GENERATED_DECKS {
        for id in rule_ids(deck) {
            let got = run_generated(deck, &id, "good");
            assert!(
                got.is_empty(),
                "{deck}: {id} fired on its good pattern: {got:?}"
            );
        }
    }
}

/// And the other half: a real violation is still caught, on every layer the deck covers.
#[test]
fn generated_bad_patterns_fire() {
    for (deck, expected) in GENERATED_DECKS {
        for id in rule_ids(deck) {
            let got = run_generated(deck, &id, "bad");
            assert_eq!(
                got,
                vec![(id.clone(), *expected)],
                "{deck}: {id} should fire {expected} time(s) on its bad pattern"
            );
        }
    }
}

// --- YMTP marker, generated ---
//
// One case per rule id, drawn inside a YMTP marker, with Dualgate over it where the rule
// is the 5 V flavour, since that is what makes a marker MV rather than LV. Y.PL.5a and
// Y.PL.5b are the same measurement upstream, so one drawing is written under both ids and
// each expects both to fire.

/// Case name, and what its bad half must produce. `None` would mark a case whose
/// violation this engine does not find; there are none at present.
type YmtpCase = (&'static str, Option<&'static [(&'static str, usize)]>);

const YMTP_CASES: &[YmtpCase] = &[
    ("Y.NW.2b_LV", Some(&[("Y.NW.2b_LV", 1)])),
    ("Y.NW.2b_MV", Some(&[("Y.NW.2b_MV", 1)])),
    ("Y.DF.16_LV", Some(&[("Y.DF.16_LV", 1)])),
    ("Y.DF.16_MV", Some(&[("Y.DF.16_MV", 1)])),
    ("Y.PL.1_LV", Some(&[("Y.PL.1_LV", 2)])),
    ("Y.PL.1_MV", Some(&[("Y.PL.1_MV", 1)])),
    ("Y.PL.2_LV", Some(&[("Y.PL.2_LV", 2)])),
    ("Y.PL.2_MV", Some(&[("Y.PL.2_MV", 2)])),
    ("Y.PL.5a_LV", Some(&[("Y.PL.5a_LV", 1), ("Y.PL.5b_LV", 1)])),
    ("Y.PL.5b_LV", Some(&[("Y.PL.5a_LV", 1), ("Y.PL.5b_LV", 1)])),
    ("Y.PL.5a_MV", Some(&[("Y.PL.5a_MV", 1), ("Y.PL.5b_MV", 1)])),
    ("Y.PL.5b_MV", Some(&[("Y.PL.5a_MV", 1), ("Y.PL.5b_MV", 1)])),
    // A gate poly crossing its COMP, measured at right angles to the crossing: the
    // source/drain overhang for Y.DF.6_MV, the poly end cap for Y.PL.4_MV. These two were
    // the fixtures that found `polys_interact`'s missing edge-crossing test.
    ("Y.DF.6_MV", Some(&[("Y.DF.6_MV", 1)])),
    ("Y.PL.4_MV", Some(&[("Y.PL.4_MV", 1)])),
];

#[test]
fn ymtp_good_patterns_are_clean() {
    for (name, _) in YMTP_CASES {
        let got = counts_at(
            "ymtp_mk",
            &format!("{GENERATED}/ymtp_mk/{name}.good.gds.gz"),
            "TOP",
        );
        assert!(got.is_empty(), "{name} fired on its good pattern: {got:?}");
    }
}

#[test]
fn ymtp_bad_patterns_fire() {
    for (name, expected) in YMTP_CASES {
        let got = counts_at(
            "ymtp_mk",
            &format!("{GENERATED}/ymtp_mk/{name}.bad.gds.gz"),
            "TOP",
        );
        match expected {
            Some(want) => {
                let want: Vec<(String, usize)> =
                    want.iter().map(|(r, n)| ((*r).to_string(), *n)).collect();
                assert_eq!(got, want, "{name} bad pattern");
            }
            None => assert!(
                got.is_empty(),
                "{name} now fires ({got:?}) — the gap this case recorded appears to be \
                 fixed, so give it its real expectation"
            ),
        }
    }
}

// --- Gate poly, generated ---

/// `PL.6` is the `no_corner` rule: poly may not turn a right angle over active area.
///
/// The good pattern says that from three sides at once — a right-angle bend clear of any
/// COMP, a 45° turn on COMP, and a right-angle bend on COMP but inside a YMTP marker,
/// which the rule exempts. A check that had collapsed to "any bend", or to "any bend on
/// COMP", fails here rather than passing.
#[test]
fn pl6_corner_patterns() {
    let good = counts_at(
        "poly2",
        &format!("{GENERATED}/poly2/PL.6.good.gds.gz"),
        "TOP",
    );
    assert!(good.is_empty(), "PL.6 fired on its good pattern: {good:?}");

    let bad = counts_at(
        "poly2",
        &format!("{GENERATED}/poly2/PL.6.bad.gds.gz"),
        "TOP",
    );
    assert_eq!(
        bad,
        vec![("PL.6".to_string(), 2)],
        "the L's two elbow corners are inside the COMP; its other four are not"
    );
}

// --- P+ poly resistor, generated ---
//
// The deck whose foundry case most needs a drawn counterpart: it reports far more markers
// per violation than we do — 219 against 39 on PRES.6 alone — so a count that is merely
// close reads as agreement and a real miss hides inside the difference. Here the clean
// half is a hard zero and the bad half has a number we chose.

/// How many markers each bad pattern is drawn to produce. One each, except where the
/// check reports per wall or the perturbation necessarily moves two things:
///
/// * `PRES.1` reports a narrow body at both its walls.
/// * `PRES.7` moves both contact heads, since the cell places them symmetrically.
fn pres_bad_expect(id: &str) -> usize {
    match id {
        "PRES.1" | "PRES.7" => 2,
        _ => 1,
    }
}

#[test]
fn pres_patterns_cover_every_rule() {
    let mut ids: Vec<String> = rule_ids("pres");
    ids.sort();
    ids.dedup(); // PRES.3 and PRES.7 are each a spacing and a must-not-touch rule
    assert_eq!(ids.len(), 9, "every rule in the section");

    for id in ids {
        let good = run_generated("pres", &id, "good");
        assert!(
            good.is_empty(),
            "pres: {id} fired on its good pattern: {good:?}"
        );
        let bad = run_generated("pres", &id, "bad");
        assert_eq!(
            bad,
            vec![(id.clone(), pres_bad_expect(&id))],
            "pres: {id}'s bad pattern should trip {id} and nothing else"
        );
    }
}

// --- P+ implant, generated ---
//
// The deck that most needed drawn patterns. Its foundry case reports 222 PP.1 markers
// where we report 392, so no count comparison on it means anything, and half the rules
// come in near/far pairs split by a 0.429 um band around a well — a classifier that has
// already caused two wrong measurements in this port. Each fixture sits deliberately on
// one side of that band and its clean half is a hard zero.

/// What each bad pattern is drawn to contain. One marker each, except:
///
/// * `PP.1` reports a narrow shape at both its walls.
/// * `PP.5b` and the `PP.5c`/`PP.5d` pairs measure an extension that is short on every
///   side of the COMP at once, so a square reports four — three for `PP.5dii`, whose
///   fourth side faces the N-well that puts it in the near bucket.
/// * `PP.3d` and `PP.3e` are the same set of geometry — COMP and Nplus and Pplus
///   together — so neither can be drawn without the other.
fn pplus_bad_expect(id: &str) -> Vec<(String, usize)> {
    let one = |i: &str| (i.to_string(), 1);
    match id {
        "PP.1" => vec![("PP.1".to_string(), 2)],
        "PP.3d" | "PP.3e" => vec![one("PP.3d"), one("PP.3e")],
        "PP.5b" | "PP.5ci" | "PP.5cii" | "PP.5di" => vec![(id.to_string(), 4)],
        "PP.5dii" => vec![("PP.5dii".to_string(), 3)],
        _ => vec![one(id)],
    }
}

#[test]
fn pplus_patterns_cover_every_rule() {
    let mut ids: Vec<String> = rule_ids("pplus");
    ids.sort();
    ids.dedup(); // PP.2 is a space and a notch rule under one id
    assert_eq!(ids.len(), 25, "every rule in the section");

    for id in ids {
        let good = run_generated("pplus", &id, "good");
        assert!(
            good.is_empty(),
            "pplus: {id} fired on its good pattern: {good:?}"
        );
        let mut bad = run_generated("pplus", &id, "bad");
        bad.sort();
        let mut want = pplus_bad_expect(&id);
        want.sort();
        assert_eq!(bad, want, "pplus: {id}'s bad pattern");
    }
}

/// The touching case `PL.5a`/`PL.5b` lose nine markers each to, reduced from the site at
/// (-3830.478, 881.684) in the foundry case: a COMP corner exactly on the gate poly's
/// boundary, the two walls collinear and meeting at that one point.
///
/// KLayout reports two separations of zero there, and so do we: one under each of the two
/// ids that share the rule. It took two changes — reading a point contact between two
/// layers as a zero gap, and making `overlapping` mean positive shared *area*, since a
/// boundary point counted as area kept this very pair out of the spacing scan that is
/// about it.
///
/// It is worth being exact about what that bought on the deck it came from, because it is
/// less than the fixture suggests. `PL.5a` went from 4 of 10 logical violations to 6 with
/// the first change and stayed at 6 through the second; the four still missing are
/// 45°-shaped, not this shape. The second change paid elsewhere — ten decks, 34 logical
/// violations — so the reduced case is a faithful minimal reproduction of *a* cause and
/// not of everything `PL.5` misses.
#[test]
fn pl5_touching_corner_is_a_zero_separation() {
    let good = counts_at(
        "poly2",
        &format!("{GENERATED}/poly2/PL.5.good.gds.gz"),
        "TOP",
    );
    assert!(good.is_empty(), "PL.5 good pattern: {good:?}");
    let bad = counts_at(
        "poly2",
        &format!("{GENERATED}/poly2/PL.5.bad.gds.gz"),
        "TOP",
    );
    assert_eq!(
        bad,
        vec![("PL.5a_LV".to_string(), 1), ("PL.5b_LV".to_string(), 1)],
        "the corner is a separation of zero, under both ids that share the rule"
    );
}

// --- OTP marker, generated ---
//
// Two rules, not the deck's sixteen. `otp_mk` has no false positives at either count and
// its misses are all pinch- or 45°-shaped, which no axis-aligned fixture reaches — the
// other fourteen would pin rules already exact against geometry that is not where the
// risk is. These two carry engine surface with almost nothing else behind it: `O.PL.2` is
// the only user anywhere of `min_width` on an edge layer, and `O.SB.11` one of two users
// of `min_overlap`, which had no drawn pattern at all.

#[test]
fn otp_mk_patterns_cover_the_new_relations() {
    for (id, bad_count) in [("O.PL.2", 2), ("O.SB.11", 1)] {
        let good = run_generated("otp_mk", id, "good");
        assert!(
            good.is_empty(),
            "otp_mk: {id} fired on its good pattern: {good:?}"
        );
        let bad = run_generated("otp_mk", id, "bad");
        assert_eq!(
            bad,
            vec![(id.to_string(), bad_count)],
            "otp_mk: {id}'s bad pattern should trip {id} and nothing else"
        );
    }
}

// --- Via, generated ---
//
// Every rule in the deck, at every level. The levels were written by expanding a
// template, which is exactly where a wrong layer slips into one of them — Via3 reaching
// for Metal3 above instead of Metal4 — so generating all four turns that from a silent
// wrong answer into a failing test.

/// The two rules the foundry documents but does not check.
fn is_guidance(suffix: &str) -> bool {
    suffix == "3.3" || suffix == "4.3"
}

/// What the bad half of each pattern is drawn to contain, by rule suffix.
///
/// Mostly the rule itself, once. Two exceptions, both structural rather than sloppy
/// drawing:
///
/// * `V#.1` reports per wall pair, so an oversized via is four.
/// * `V#.3c`/`V#.4b` cannot avoid also tripping `V#.3d`/`V#.4c`. A 0.26 µm via in a
///   track narrow enough to have a line end — under 0.34 µm — has sidewalls under 0.04,
///   so a thin tip always leaves a short side whose neighbours are short too. The two
///   rules genuinely overlap on that geometry; there is no way to draw one without the
///   other.
fn via_bad_expect(level: usize, suffix: &str) -> Vec<(String, usize)> {
    let id = |sfx: &str| (format!("V{level}.{sfx}"), 1);
    match suffix {
        "1" => vec![(format!("V{level}.1"), 4)],
        "3c" => vec![id("3c"), id("3d")],
        "4b" => vec![id("4b"), id("4c")],
        _ => vec![id(suffix)],
    }
}

#[test]
fn via_patterns_cover_every_rule() {
    let mut ids: Vec<String> = rule_ids("via");
    ids.sort();
    ids.dedup(); // V#.2a is a space and a notch rule under one id
    assert_eq!(ids.len(), 44, "eleven rules at each of four levels");

    for id in ids {
        let (level, suffix) = id.split_once('.').expect("V<n>.<rule>");
        let level: usize = level[1..].parse().expect("V<n>");

        // V#.3.3 and V#.4.3 ask for 0.12 µm where the rules require 0.01, so they fire on
        // any via not drawn generously — including the *legal* half of patterns whose
        // point is a small margin. `V#.3.1`'s good pattern is exactly that: it keeps the
        // same 0.02 µm margin as its bad half and only widens the track, which is what
        // says the rule is about the line end rather than the number. So the guidance
        // rules are asserted by their own two fixtures and filtered out of every other,
        // where they say nothing about the rule at hand. That they cannot be avoided here
        // is the same property that keeps them out of `main`.
        let drop_guidance = |c: &mut Vec<(String, usize)>| {
            if !is_guidance(suffix) {
                c.retain(|(r, _)| !is_guidance(r.split_once('.').expect("V<n>.<rule>").1));
            }
        };

        let mut good = counts_at("via", &format!("{GENERATED}/via/{id}.good.gds.gz"), "TOP");
        drop_guidance(&mut good);
        assert!(good.is_empty(), "{id} fired on its good pattern: {good:?}");

        let mut bad = counts_at("via", &format!("{GENERATED}/via/{id}.bad.gds.gz"), "TOP");
        drop_guidance(&mut bad);
        let mut want = via_bad_expect(level, suffix);
        want.sort();
        assert_eq!(bad, want, "{id} bad pattern");
    }
}
